name: my_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_database: ^11.3.3
  firebase_storage: ^12.4.3
  image_picker: ^1.0.7
  riverpod: ^3.0.0-dev.3
  flutter_riverpod: ^3.0.0-dev.3
  go_router: ^14.8.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^3.0.0-dev.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^3.0.0-dev.11

flutter:
  uses-material-design: true
  assets:
    - assets/icon_1.svg
    - assets/home_image.svg
    - assets/products/laptop.jpeg
    - assets/products/speaker.jpeg
    - assets/products/watch.jpeg
    - assets/products/iphone_13.jpeg
    - assets/products/ikea_desk.jpeg
    - assets/products/samsung_tv.jpeg
    - assets/products/macbook_pro.jpeg
    - assets/products/dyson_vacuum.jpeg
    - assets/products/nike_air_max.jpeg
    - assets/products/canon_camera.jpeg
