name: my_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  riverpod: ^3.0.0-dev.3
  flutter_riverpod: ^3.0.0-dev.3
  go_router: ^14.8.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^3.0.0-dev.3
  riverpod_annotation: ^3.0.0-dev.3
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  freezed_annotation: ^2.4.1
  firebase_storage: ^11.7.7
  simple_logger: ^1.10.0
  mime: ^1.0.4
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^3.0.0-dev.3
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon_1.svg
    - assets/home_image.svg
    - assets/products/laptop.jpeg
    - assets/products/speaker.jpeg
    - assets/products/watch.jpeg
    - assets/products/iphone_13.jpeg
    - assets/products/ikea_desk.jpeg
    - assets/products/samsung_tv.jpeg
    - assets/products/macbook_pro.jpeg
    - assets/products/dyson_vacuum.jpeg
    - assets/products/nike_air_max.jpeg
    - assets/products/canon_camera.jpeg