name: my_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  riverpod: ^2.4.9
  flutter_riverpod: ^2.5.1
  go_router: ^14.8.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.5
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon_1.svg
    - assets/home_image.svg
    - assets/products/laptop.jpeg
    - assets/products/speaker.jpeg
    - assets/products/watch.jpeg
    - assets/products/iphone_13.jpeg
    - assets/products/ikea_desk.jpeg
    - assets/products/samsung_tv.jpeg
    - assets/products/macbook_pro.jpeg
    - assets/products/dyson_vacuum.jpeg
    - assets/products/nike_air_max.jpeg
    - assets/products/canon_camera.jpeg