name: Flutter Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    name: Flutter Code Analysis
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'   # This automatically uses the latest stable version
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get
          flutter pub upgrade --major-versions   # Ensures all dependencies are updated

      - name: Generate Code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze Flutter
        run: flutter analyze --fatal-infos --fatal-warnings
